---
-  hosts: webservers
   become: yes
   remote_user: ubuntu
   tasks:
   - name: Instalando o Nginx
     apt:
       name: nginx
       state: latest
       update_cache: yes

   - name: habilitando o start do Nginx no boot
     service:
       name: nginx
       enabled: yes

   - name: Iniciando Nginx
     service:
       name: nginx
       state: started
    
   - name: copiando html personalizado
     template:
       src: index.html.j2
       dest: /var/www/html/index.html
   
   - name: copiando nginx  personalizado
     copy:
       src: nginx.conf
       dest: /etc/nginx/nginx.conf
     notify: Restartando o Nginx  
   
   handlers:
   - name: Restartando o Nginx
     service:
       name: nginx
       state: restarted
